#!/bin/sh
#Credit (CC BY-SA 3.0): https://unix.stackexchange.com/a/217024
if [ "$(/usr/bin/id -u)" -ne "0" ]; then echo -e 'This script needs to be run as root!'; exit 1; fi;

if [ -f /etc/fedora-release ] || [ -f /etc/centos-release ]; then
	echo -e "Verifying installed packages"
	echo -e "This script is *not* for security purposes, but instead to fix broken packages.";
	dnf reinstall $(rpm -qf $(rpm -Va 2>&1 | grep -vE '^$|prelink:' | sed 's|.* /|/|') | sort -u | grep -v -e "kernel-" -e "fedora-" -e "setup" -e "grub2-");
else
	echo -e "Currently only Fedora and CentOS are supported";
fi;
