#!/bin/sh

if [ "$(/usr/bin/id -u)" -ne "0" ]; then echo 'This script needs to be run as root!'; exit 1; fi;

if [ -f /etc/fedora-release ]; then
	echo "Setting up Android debugging...";
fi;

if [ -f /etc/fedora-release ]; then
	dnf install android-tools enjarify;
	dnf update --refresh;
	dnf copr enable nielsenb/android-udev-rules;
	dnf install android-udev-rules;
else
	echo "Currently only Fedora is supported";
fi;
