#!/bin/sh

if [ "$(/usr/bin/id -u)" -ne "0" ]; then echo 'This script needs to be run as root!'; exit 1; fi;

if [ -f /etc/fedora-release ]; then
	echo "Installing Brave Browser";
fi;

if [ -f /etc/fedora-release ]; then
	dnf config-manager --add-repo https://brave-browser-rpm-release.s3.brave.com/brave-browser.repo;
	rpm --import https://brave-browser-rpm-release.s3.brave.com/brave-core.asc;
	dnf update --refresh;
	dnf install brave-browser;
else
	echo "Currently only Fedora is supported";
fi;
