#!/bin/bash

coloroff='\e[0m';
black='\e[0;30m';
blue='\e[0;34m';
cyan='\e[0;36m';
green='\e[0;32m';
purple='\e[0;35m';
red='\e[0;31m';
white='\e[0;37m';
yellow='\e[0;33m';

if [ "$(/usr/bin/id -u)" -ne "0" ]; then echo -e "${red}ERROR: This script needs to be run as root!${coloroff}"; exit 1; fi;

if [ -f /etc/fedora-release ]; then

	echo -e "${red}Cleaning up DNF...${coloroff}";
	dnf autoremove;
	dnf clean all -y;

	echo -e "${red}Updating DNF Cache...${coloroff}";
	dnf update --refresh -y;

	echo -e "${red}Adding DNF Repositories...${coloroff}";
	dnf config-manager addrepo --id=brave-browser --set=name='Brave Browser' --set=baseurl='https://brave-browser-rpm-release.s3.brave.com/$basearch' -y;
	rpm --import https://brave-browser-rpm-release.s3.brave.com/brave-core.asc;
	dnf copr enable secureblue/hardened-chromium -y;
	dnf config-manager addrepo --from-repofile='https://repository.mullvad.net/rpm/stable/mullvad.repo' -y;
	dnf config-manager addrepo --from-repofile='https://slingshot.celenity.dev/vscodium.repo' -y;
	dnf config-manager addrepo --from-repofile='https://repo.ivpn.net/stable/fedora/generic/ivpn.repo' -y;

	echo -e "${red}Updating DNF Cache...${coloroff}";
	dnf update --refresh -y;

	echo -e "${red}Updating Flatpak Cache...${coloroff}";
	flatpak --system update -y;
	flatpak --user update -y;

	echo -e "${red}Updating Firejail...${coloroff}";
	firecfg;
	
	echo -e "${red}Installing Brave...${coloroff}";
	dnf install brave-browser -y;

	echo -e "${red}Installing Hardened Chromium...${coloroff}";
	dnf install hardened-chromium -y;

	echo -e "${red}Installing Mullvad Browser...${coloroff}";
	dnf install mullvad-browser -y;

	echo -e "${red}Installing Tor Browser...${coloroff}";
	dnf install tor torbrowser-launcher -y;

	echo -e "Installing Fedora's Recommended Developer Tools...";
	echo -e "${red}Installing the "Development Tools" group...${coloroff}";
	dnf group install development-tools -y;

	echo -e "${red}Installing General Development Languages/Support/Dependencies...${coloroff}";
	dnf install cargo cmake coreutils copr-rpmbuild fedpkg git-core make maven mercurial mock pacman perl proguard rpkg rpm-build rpmdevtools rpmlint ruby rust -y;
	
	echo -e "${red}Installing nano...${coloroff}";
	dnf install nano -y;

	echo -e "${red}Installing VSCodium...${coloroff}";
	dnf install codium -y;

	echo -e "${red}Installing ADB...${coloroff}";
	dnf install android-tools -y;

	echo -e "Installing Android Studio...";
	echo -e "${red}Installing Android Studio...${coloroff}";
	flatpak --user install com.google.AndroidStudio -y;
	echo -e "${red}Granting Android Studio necessary permissions...${coloroff}";
	flatpak --user override com.google.AndroidStudio --device=dri --device=kvm --share=network;

	echo -e "${red}Installing enjarify...${coloroff}";
	dnf install enjarify -y;

	echo -e "Installing Fedora's Recommended Virtualization Software...";
	echo -e "${red}Installing the "Virtualization" group...${coloroff}";
	dnf group install virtualization --with-optional -y;

	echo -e "${red}Installing Signal...${coloroff}";
	flatpak --user install org.signal.Signal -y;
	echo -e "${red}Granting Signal necessary permissions...${coloroff}";
	flatpak --user override org.signal.Signal --share=network --socket=pulseaudio;

	echo -e "${red}Installing VLC...${coloroff}";
	flatpak --user install org.videolan.VLC org.videolan.VLC.Plugin.pause_click org.videolan.VLC.Plugin.fdkaac org.videolan.VLC.Plugin.bdj org.videolan.VLC.Plugin.makemkv -y;
	echo -e "${red}Granting VLC necessary permissions...${coloroff}";
	flatpak --user override org.videolan.VLC --device=dri --socket=pulseaudio --nosocket=wayland --socket=fallback-x11;
	
	echo -e "${red}Installing Lollypop...${coloroff}";
	flatpak --user install org.gnome.Lollypop -y;
	
	echo -e "${red}Installing qBittorrent...${coloroff}";
	flatpak --user install org.qbittorrent.qBittorrent -y;
	echo -e "${red}Granting qBittorrent necessary permissions...${coloroff}";
	flatpak --user override org.qbittorrent.qBittorrent --share=network;

	echo -e "${red}Installing Finamp..${coloroff}";
	flatpak --user install com.unicornsonlsd.finamp -y;
	echo -e "${red}Granting Finamp necessary permissions...${coloroff}";
	flatpak --user override com.unicornsonlsd.finamp --share=network --socket=pulseaudio; 

	echo -e "${red}Installing OBS...${coloroff}";
	flatpak --user install com.obsproject.Studio com.obsproject.Studio.Plugin.InputOverlay com.obsproject.Studio.Plugin.Gstreamer com.obsproject.Studio.Plugin.GStreamerVaapi com.obsproject.Studio.Plugin.CompositeBlur com.obsproject.Studio.Plugin.BackgroundRemoval -y;
	echo -e "${red}Granting OBS necessary permissions...${coloroff}";
	flatpak --user override com.obsproject.Studio --device=dri --socket=pulseaudio;

	echo -e "${red}Installing WINE...${coloroff}";
	dnf install wine -y;
	dnf install winetricks -y;

	echo -e "${red}Installing IVPN...${coloroff}";
	dnf install ivpn ivpn-ui -y;
	
	echo -e "${red}Installing Obsidian...${coloroff}";
	flatpak --user install md.obsidian.Obsidian -y;
	echo -e "${red}Granting Obsidian necessary permissions...${coloroff}";
	mkdir -p ~/Documents/Obsidian;
	flatpak --user override md.obsidian.Obsidian --share=network --filesystem=xdg-documents/Obsidian;

	echo -e "Install MakeMKV? (Flatpak)";
		select yn in "Yes" "No"; do
			case $yn in
					Yes )
						echo -e "${red}Installing MakeMKV...${coloroff}";
						flatpak --user install com.makemkv.MakeMKV -y;
						echo -e "${red}Granting MakeMKV necessary permissions...${coloroff}";
						flatpak --user override com.makemkv.MakeMKV --device=all --share=network;
						break;;
					No )
						break;;
				esac
			done

	echo -e "Install Asunder? (Flatpak)";
		select yn in "Yes" "No"; do
			case $yn in
					Yes )
						echo -e "${red}Installing Asunder...${coloroff}";
						flatpak --user install ca.littlesvr.asunder;
						echo -e "${red}Granting Asunder necessary permissions...${coloroff}";
						mkdir -p ~/Music/Asunder;
						flatpak --user override ca.littlesvr.asunder --socket=x11 --device=all --share=network --filesystem=xdg-music/Asunder;
						break;;
					No )
						break;;
				esac
			done

	echo -e "Install Audacity? (Flatpak)";
		select yn in "Yes" "No"; do
			case $yn in
					Yes )
						echo -e "${red}Installing Audacity...${coloroff}";
						flatpak --user install org.audacityteam.Audacity -y;
						echo -e "${red}Granting Audacity necessary permissions...${coloroff}";
						flatpak --user override org.audacityteam.Audacity --socket=pulseaudio;
						break;;
					No )
						break;;
				esac
			done

	echo -e "Install Steam (Flatpak)?";
		select yn in "Yes" "No"; do
			case $yn in
					Yes )
						echo -e "${red}Installing Steam...${coloroff}";
						flatpak --user install com.valvesoftware.Steam com.valvesoftware.Steam.Utility.steamtinkerlaunch com.valvesoftware.Steam.CompatibilityTool.Proton-GE com.valvesoftware.Steam.Utility.InhibitScreensaver -y;
						echo -e "${red}Granting Steam necessary permissions...${coloroff}";
						flatpak --user override com.valvesoftware.Steam --nosocket=wayland --socket=fallback-x11 --device=dri --share=network --socket=pulseaudio --nosocket=wayland --socket=fallback-x11;
						echo -e "${red}Disabling hardened_malloc for Steam (Causes it to break)...${coloroff}";
						flatpak --user override com.valvesoftware.Steam --nofilesystem=host-os --unset-env=LD_PRELOAD;
						break;;
					No )
						break;;
				esac
			done

	echo -e "Install Prism Launcher? (Minecraft, Flatpak)";
		select yn in "Yes" "No"; do
			case $yn in
					Yes )
						echo -e "${red}Installing Prism Launcher...${coloroff}";
						flatpak --user install org.prismlauncher.PrismLauncher -y;
						echo -e "${red}Granting Prism Launcher necessary permissions...${coloroff}";
						flatpak --user override org.prismlauncher.PrismLauncher --device=dri --share=network --socket=pulseaudio;
						break;;
					No )
						break;;
				esac
			done

	echo -e "Protontricks? (Flatpak)";
				select yn in "Yes" "No"; do
					case $yn in
							Yes )
								echo -e "${red}Installing Protontricks...${coloroff}";
								flatpak --user install com.github.Matoking.protontricks -y;
								break;;
							No )
								break;;
						esac
					done

	echo -e "ProtonUp-Qt? (Flatpak)";
				select yn in "Yes" "No"; do
					case $yn in
							Yes )
								echo -e "${red}Installing ProtonUp-Qt...${coloroff}";
								flatpak --user install net.davidotek.pupgui2 -y;
								echo -e "${red}Granting ProtonUp-Qt necessary permissions...${coloroff}";
								flatpak --user override net.davidotek.pupgui2 --share=network;
								break;;
							No )
								break;;
						esac
					done

	echo -e "${red}Cleaning up DNF...${coloroff}";
	dnf autoremove;
	dnf clean all -y;

	echo -e "${red}Updating DNF Cache...${coloroff}";
	dnf update --refresh -y;

	echo -e "${red}Updating Flatpak Cache...${coloroff}";
	flatpak --system update -y;
	flatpak --user update -y;

	echo -e "${red}Updating Firejail...${coloroff}";
	firecfg;

fi;