#!/bin/sh
#Copyright (c) 2024 celenity, 2018-2020 Divested Computing Group
#
#This program is free software: you can redistribute it and/or modify
#it under the terms of the GNU Affero General Public License as published by
#the Free Software Foundation, either version 3 of the License, or
#(at your option) any later version.
#
#This program is distributed in the hope that it will be useful,
#but WITHOUT ANY WARRANTY; without even the implied warranty of
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#GNU Affero General Public License for more details.
#
#You should have received a copy of the GNU Affero General Public License
#along with this program.  If not, see <https://www.gnu.org/licenses/>.

if [ "$(/usr/bin/id -u)" -ne "0" ]; then echo -e 'This script needs to be run as root!'; exit 1; fi;

if [ -f /etc/fedora-release ] || [ -f /etc/centos-release ]; then
	echo -e "Enabling RPM Fusion, Divested RPM, & replacing system Flathub with user Flathub";
	echo -e "Please verify the RPM Fusion signing keys from here: https://rpmfusion.org/keys";
	echo -e "Free - F33-40: E9A4 91A3 DE24 7814 E7E0 67EA E06F 8ECD D651 FF2E";
	echo -e "Free - EL9: EDC0 0FE7 418C 9DF7 EF49  91A4 7403 EA33 2964 58F3";
	echo -e "Free - EL8: 8379 35CD 19E1 23AA 7F8A  8E69 979F 0C69 158B 3811";
	echo -e "Free - EL7: DB9A 9A57 CAFD 23DA 3A88  792F 758B 3D18 F5CF 6C1E";
	echo -e "Nonfree - F33-40: 79BD B88F 9BBF 7391 0FD4 095B 6A2A F961 9484 3C65";
	echo -e "Nonfree - EL9: BB24 128A 4BB3 C335 2C0B  75A2 E417 4E6B AAB2 12EA";
	echo -e "Nonfree - EL8: CF9F D59F 61D6 6121 46CD AC8E 14B6 792D BDDA 8475";
	echo -e "Nonfree - EL7: C3FA F3A9 6B39 8583 91ED  D8D9 C8F7 6DF1 A310 8F6C";
fi

if [ -f /etc/fedora-release ]; then
	dnf install "https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm";
	dnf install "https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm";
	dnf remove fedora-third-party fedora-workstation-repositories;
	dnf config-manager --add-repo https://codeberg.org/divested/divested-release/raw/branch/master/divested-release.repo;
	dnf update --refresh;
	dnf remove fedora-flathub-remote
	flatpak remote-delete --system flathub
	flatpak remote-add --if-not-exists --user flathub https://dl.flathub.org/repo/flathub.flatpakrepo;
	flatpak update
elif [ -f /etc/centos-release ]; then
	yum install epel-release;
	yum localinstall --nogpgcheck "https://download1.rpmfusion.org/free/el/rpmfusion-free-release-$(rpm -E %centos).noarch.rpm";
	yum localinstall --nogpgcheck "https://download1.rpmfusion.org/nonfree/el/rpmfusion-nonfree-release-$(rpm -E %centos).noarch.rpm";
else
	echo -e "Currently only Fedora and CentOS are supported";
fi
