#!/bin/bash

coloroff='\e[0m';
black='\e[0;30m';
blue='\e[0;34m';
cyan='\e[0;36m';
green='\e[0;32m';
purple='\e[0;35m';
red='\e[0;31m';
white='\e[0;37m';
yellow='\e[0;33m';

if [ "$(/usr/bin/id -u)" -ne "0" ]; then echo -e "${red}ERROR: This script needs to be run as root!${coloroff}"; exit 1; fi;

if [ -f /etc/fedora-release ]; then
	echo -e "${purple}Welcome! This will allow you to easily install high-quality software from different categories.${coloroff}";
	echo -e "${purple}Nothing will be installed without your permission. You will be asked for each app.${coloroff}";
	echo -e "${purple}If you don't want any apps from a category, you can simply choose no to skip it!${coloroff}";
	echo -e "";

	echo -e "${red}Cleaning up DNF...${coloroff}";
	dnf autoremove;
	dnf clean all;

	echo -e "${red}Updating DNF Cache...${coloroff}";
	dnf update --refresh;

	echo -e "${red}Updating Flatpak Cache...${coloroff}";
	flatpak --system update;
	flatpak --user update;

	echo -e "${red}Updating Firejail...${coloroff}";
	firecfg;

	echo -e "Would you like to install any web browsers?";
	select yn in "Yes" "No"; do
		case $yn in
			Yes )
				echo -e "Firefox? (RPM, Recommended, Preinstalled)";
				select yn in "Yes" "No"; do
					case $yn in
							Yes )
								echo -e "${red}Updating DNF Cache...${coloroff}";
								dnf update --refresh;
								echo -e "${red}Installing Firefox...${coloroff}";
								dnf install firefox;
								echo -e "Harden with Phoenix? https://phoenix.celenity.dev (Recommended)";
								select yn in "Yes" "No"; do
									case $yn in
										Yes )
											bash -c "$(curl -fsSL https://phoenix.celenity.dev/fedora_install.sh)";
											break;;
										No )
											break;;
										esac
									done
								break;;
							No )
								break;;
						esac
					done
				echo -e "Brave? (RPM)";
				select yn in "Yes" "No"; do
					case $yn in
							Yes )
								echo -e "${red}Adding Brave's Repository...${coloroff}";
								dnf config-manager addrepo --id=brave-browser --set=name='Brave Browser' --set=baseurl='https://brave-browser-rpm-release.s3.brave.com/$basearch';
								rpm --import https://brave-browser-rpm-release.s3.brave.com/brave-core.asc;
								echo -e "${red}Updating DNF Cache...${coloroff}";
								dnf update --refresh;
								echo -e "${red}Installing Brave...${coloroff}";
								dnf install brave-browser;
								break;;
							No )
								break;;
						esac
					done
				echo -e "Hardened Chromium? (RPM)";
				select yn in "Yes" "No"; do
					case $yn in
							Yes )
								echo -e "${red}Adding secureblue's hardened-chromium COPR...${coloroff}";
								dnf copr enable secureblue/hardened-chromium;
								echo -e "${red}Updating DNF Cache...${coloroff}";
								dnf update --refresh;
								echo -e "${red}Installing Hardened Chromium...${coloroff}";
								dnf install hardened-chromium;
								break;;
							No )
								break;;
						esac
					done
				echo -e "Mullvad Browser? (RPM)";
				select yn in "Yes" "No"; do
					case $yn in
							Yes )
								echo -e "${red}Adding Mullvad's Repository...${coloroff}";
								dnf config-manager addrepo --from-repofile='https://repository.mullvad.net/rpm/stable/mullvad.repo';
								echo -e "${red}Updating DNF Cache...${coloroff}";
								dnf update --refresh;
								echo -e "${red}Installing Mullvad Browser...${coloroff}";
								dnf install mullvad-browser;
								break;;
							No )
								break;;
						esac
					done
				echo -e "Tor Browser? (RPM)";
				select yn in "Yes" "No"; do
					case $yn in
							Yes )
								echo -e "${red}Updating DNF Cache...${coloroff}";
								dnf update --refresh;
								echo -e "${red}Installing Tor Browser...${coloroff}";
								dnf install tor torbrowser-launcher;
								break;;
							No )
								break;;
						esac
					done		
				break;;
			No )
				break;;
		esac
	done

	echo -e "Would you like to install software for Development?";
	select yn in "Yes" "No"; do
		case $yn in
			Yes )
				echo -e "Fedora's Recommended Developer Tools? (RPM)";
				select yn in "Yes" "No"; do
					case $yn in
							Yes )
								echo -e "${red}Updating DNF Cache...${coloroff}";
								dnf update --refresh;
								echo -e "${red}Installing the "Development Tools" group...${coloroff}";
								dnf group install development-tools;
								break;;
							No )
								break;;
						esac
					done
				echo -e "General Development Languages/Support/Dependencies? (RPM)";
				select yn in "Yes" "No"; do
					case $yn in
							Yes )
								echo -e "${red}Updating DNF Cache...${coloroff}";
								dnf update --refresh;
								echo -e "${red}Installing General Development Languages/Support/Dependencies...${coloroff}";
								dnf install cargo cmake coreutils copr-rpmbuild fedpkg git-core make maven mercurial mock pacman perl proguard rpkg rpm-build rpmdevtools rpmlint ruby rust;
								break;;
							No )
								break;;
						esac
					done				
				echo -e "nano? (RPM)";
				select yn in "Yes" "No"; do
					case $yn in
							Yes )
								echo -e "${red}Installing nano...${coloroff}";
								dnf install nano;
								break;;
							No )
								break;;
						esac
					done
				echo -e "VSCodium? (RPM)";
				select yn in "Yes" "No"; do
					case $yn in
							Yes )
								echo -e "${red}Adding VSCodium's Repository...${coloroff}";
								dnf config-manager addrepo --from-repofile='https://slingshot.celenity.dev/vscodium.repo';
								echo -e "${red}Updating DNF cache...${coloroff}";
								dnf update --refresh;
								echo -e "${red}Installing VSCodium...${coloroff}";
								dnf install codium;
								break;;
							No )
								break;;
						esac
					done
				break;;
			No )
				break;;
		esac
	done

	echo -e "Would you like to install software for compatibility with Android devices?";
	select yn in "Yes" "No"; do
		case $yn in
			Yes )
				echo -e "ADB? (RPM)";
				select yn in "Yes" "No"; do
					case $yn in
							Yes )
								echo -e "${red}Installing ADB...${coloroff}";
								dnf install android-tools;
								break;;
							No )
								break;;
						esac
					done
				echo -e "Android Studio? (Flatpak)";
				select yn in "Yes" "No"; do
					case $yn in
							Yes )
								echo -e "${red}Installing Android Studio...${coloroff}";
								flatpak --user install com.google.AndroidStudio;
								echo -e "${red}Granting Android Studio necessary permissions...${coloroff}";
								mkdir -p ~/.android;
								flatpak --user override com.google.AndroidStudio --device=dri --device=kvm --share=network --filesystem=~/.android;
								break;;
							No )
								break;;
						esac
					done				
				echo -e "enjarify? (RPM)";
				select yn in "Yes" "No"; do
					case $yn in
							Yes )
								echo -e "${red}Installing enjarify...${coloroff}";
								dnf install enjarify;
								break;;
							No )
								break;;
						esac
					done
				break;;
			No )
				break;;
		esac
	done

	echo -e "Would you like to install software for virtualization?";
	select yn in "Yes" "No"; do
		case $yn in
			Yes )
				echo -e "Fedora's Recommended Virtualization Software? (RPM)";
				select yn in "Yes" "No"; do
					case $yn in
							Yes )
								echo -e "${red}Installing the "Virtualization" group...${coloroff}";
								dnf group install virtualization --with-optional;
								break;;
							No )
								break;;
						esac
					done
				break;;
			No )
				break;;
		esac
	done

	echo -e "Would you like to install software for communication?";
	select yn in "Yes" "No"; do
		case $yn in
			Yes )
				echo -e "Signal? (Flatpak, Recommended)";
				select yn in "Yes" "No"; do
					case $yn in
							Yes )
								echo -e "${red}Installing Signal...${coloroff}";
								flatpak --user install org.signal.Signal;
								echo -e "${red}Signal will not function without network access.${coloroff}";
								echo -e "Do you grant this permission?";
								select yn in "Yes" "No"; do
									case $yn in
										Yes )
											flatpak --user override org.signal.Signal --share=network;
											break;;
										No )
											break;;
										esac
									done
								echo -e "${red}Signal requires access to PulseAudio for audio input & playback.${coloroff}";
								echo -e "Do you grant this permission?";
								select yn in "Yes" "No"; do
									case $yn in
										Yes )
											flatpak --user override org.signal.Signal --socket=pulseaudio;
											break;;
										No )
											break;;
										esac
									done
								echo -e "${red}Signal requires access to your connected devices for sharing your webcam.${coloroff}";
								echo -e "Do you grant this permission?";
								select yn in "Yes" "No"; do
									case $yn in
										Yes )
											flatpak --user override org.signal.Signal --device=all;
											break;;
										No )
											break;;
										esac
									done
								break;;
							No )
								break;;
						esac
					done
				echo -e "Thunderbird? (RPM, Recommended)";
				select yn in "Yes" "No"; do
					case $yn in
							Yes )
								echo -e "${red}Installing Thunderbird...${coloroff}";
								dnf install thunderbird;
								echo -e "Harden with Dove? https://dove.celenity.dev (Recommended)";
								select yn in "Yes" "No"; do
									case $yn in
										Yes )
											bash -c "$(curl -fsSL https://dove.celenity.dev/fedora_install.sh)";
											break;;
										No )
											break;;
										esac
									done
								break;;
							No )
								break;;
						esac
					done
				echo -e "Proton Mail Bridge? (Flatpak)";
				select yn in "Yes" "No"; do
					case $yn in
							Yes )
								echo -e "${red}Installing Proton Mail Bridge...${coloroff}";
								flatpak --user install ch.protonmail.protonmail-bridge;
								echo -e "${red}Proton Mail Bridge will not function without network access.${coloroff}";
								echo -e "Do you grant this permission?";
								select yn in "Yes" "No"; do
									case $yn in
										Yes )
											flatpak --user override ch.protonmail.protonmail-bridge --share=network;
											break;;
										No )
											break;;
										esac
									done
								break;;
							No )
								break;;
						esac
					done
				break;;
			No )
				break;;
		esac
	done

	echo -e "Would you like to install software for Finance?";
	select yn in "Yes" "No"; do
		case $yn in
			Yes )
				echo -e "Cake Wallet? (Flatpak)";
				select yn in "Yes" "No"; do
					case $yn in
							Yes )
								echo -e "${red}Downloading Cake Wallet...${coloroff}";
								wget https://github.com/cake-tech/cake_wallet/releases/download/v4.20.1/Cake_Wallet_v4.20.1_Linux.flatpak;
								echo -e "${red}Installing Cake Wallet...${coloroff}";
								flatpak --user install Cake_Wallet_v4.20.1_Linux.flatpak;
								echo -e "${red}Cake Wallet will not launch with hardened_malloc.${coloroff}";
								echo -e "Do you grant it an exception?";
								select yn in "Yes" "No"; do
									case $yn in
										Yes )
											flatpak --user override com.cakewallet.CakeWallet --nofilesystem=host-os --unset-env=LD_PRELOAD;
											break;;
										No )
											break;;
										esac
									done
								echo -e "${red}Cake Wallet will not function without network access.${coloroff}";
								echo -e "Do you grant this permission?";
								select yn in "Yes" "No"; do
									case $yn in
										Yes )
											flatpak --user override com.cakewallet.CakeWallet --share=network;
											break;;
										No )
											break;;
										esac
									done
								break;;
							No )
								break;;
						esac
					done
				break;;
			No )
				break;;
		esac
	done

	echo -e "Would you like to install software for media consumption?";
	select yn in "Yes" "No"; do
		case $yn in
			Yes )
				echo -e "VLC? (Flatpak)";
				select yn in "Yes" "No"; do
					case $yn in
							Yes )
								echo -e "${red}Removing RPM if already installed...${coloroff}";
								dnf remove vlc;
								echo -e "${red}Installing VLC...${coloroff}";
								flatpak --user install org.videolan.VLC org.videolan.VLC.Plugin.pause_click org.videolan.VLC.Plugin.fdkaac org.videolan.VLC.Plugin.bdj org.videolan.VLC.Plugin.makemkv;
								echo -e "${red}VLC will not launch without access to the X11 windowing system.${coloroff}";
								echo -e "Do you grant this permission?";
								select yn in "Yes" "No"; do
									case $yn in
										Yes )
											flatpak --user override org.videolan.VLC --nosocket=wayland --socket=fallback-x11;
											break;;
										No )
											break;;
										esac
									done
								echo -e "${red}VLC requires access to PulseAudio for audio playback.${coloroff}";
								echo -e "Do you grant this permission?";
								select yn in "Yes" "No"; do
									case $yn in
										Yes )
											flatpak --user override org.videolan.VLC --socket=pulseaudio;
											break;;
										No )
											break;;
										esac
									done
								echo -e "${red}VLC requires direct access to your GPU for hardware acceleration.${coloroff}";
								echo -e "Do you grant this permission?";
								select yn in "Yes" "No"; do
									case $yn in
										Yes )
											flatpak --user override org.videolan.VLC --device=dri;
											break;;
										No )
											break;;
										esac
									done
								echo -e "${red}VLC requires network access for downloading & updating metadata.${coloroff}";
								echo -e "Do you grant this permission?";
								select yn in "Yes" "No"; do
									case $yn in
										Yes )
											flatpak --user override org.videolan.VLC --share=network;
											break;;
										No )
											break;;
										esac
									done
								break;;
							No )
								break;;
						esac
					done
				echo -e "Lollypop? (Flatpak)";
				select yn in "Yes" "No"; do
					case $yn in
							Yes )
								echo -e "${red}Removing RPM if already installed...${coloroff}";
								dnf remove lollypop;
								echo -e "${red}Installing Lollypop...${coloroff}";
								flatpak --user install org.gnome.Lollypop;
								echo -e "${red}Lollypop requires access to PulseAudio for audio playback.${coloroff}";
								echo -e "Do you grant this permission?";
								select yn in "Yes" "No"; do
									case $yn in
										Yes )
											flatpak --user override org.gnome.Lollypop --socket=pulseaudio;
											break;;
										No )
											break;;
										esac
									done
								echo -e "${red}Lollypop requires network access for downloading & updating metadata.${coloroff}";
								echo -e "Do you grant this permission?";
								select yn in "Yes" "No"; do
									case $yn in
										Yes )
											flatpak --user override org.gnome.Lollypop --share=network;
											break;;
										No )
											break;;
										esac
									done
								break;;
							No )
								break;;
						esac
					done
				echo -e "qBittorrent? (Flatpak)";
				select yn in "Yes" "No"; do
					case $yn in
							Yes )
								echo -e "${red}Removing RPM if already installed...${coloroff}";
								dnf remove qbittorrent;
								echo -e "${red}Installing qBittorrent...${coloroff}";
								flatpak --user install org.qbittorrent.qBittorrent;
								echo -e "${red}qBittorrent will not function without network access.${coloroff}";
								echo -e "Do you grant this permission?";
								select yn in "Yes" "No"; do
									case $yn in
										Yes )
											flatpak --user override org.qbittorrent.qBittorrent --share=network;
											break;;
										No )
											break;;
										esac
									done
								break;;
							No )
								break;;
						esac
					done
				echo -e "Kodi? (Flatpak)";
				select yn in "Yes" "No"; do
					case $yn in
							Yes )
								echo -e "${red}Removing RPM if already installed...${coloroff}";
								dnf remove kodi;
								echo -e "${red}Installing Kodi...${coloroff}";
								flatpak --user install tv.kodi.Kodi;
								echo -e "${red}Kodi requires access to PulseAudio for audio playback.${coloroff}";
								echo -e "Do you grant this permission?";
								select yn in "Yes" "No"; do
									case $yn in
										Yes )
											flatpak --user override tv.kodi.Kodi --socket=pulseaudio;
											break;;
										No )
											break;;
										esac
									done
								echo -e "${red}Kodi requires direct access to your GPU for hardware acceleration.${coloroff}";
								echo -e "Do you grant this permission?";
								select yn in "Yes" "No"; do
									case $yn in
										Yes )
											flatpak --user override tv.kodi.Kodi --device=dri;
											break;;
										No )
											break;;
										esac
									done
								echo -e "${red}Kodi requires network access for remote playback & add-on installation/updates.${coloroff}";
								echo -e "Do you grant this permission?";
								select yn in "Yes" "No"; do
									case $yn in
										Yes )
											flatpak --user override tv.kodi.Kodi --share=network;
											break;;
										No )
											break;;
										esac
									done
								break;;
							No )
								break;;
						esac
					done
				echo -e "NewPipe? (Flatpak)";
				select yn in "Yes" "No"; do
					case $yn in
							Yes )
								echo -e "${red}Installing NewPipe..${coloroff}";
								flatpak --user install net.newpipe.NewPipe;
								echo -e "${red}NewPipe will not function without network access.${coloroff}";
								echo -e "Do you grant this permission?";
								select yn in "Yes" "No"; do
									case $yn in
										Yes )
											flatpak --user override net.newpipe.NewPipe --share=network;
											break;;
										No )
											break;;
										esac
									done
								echo -e "${red}NewPipe requires access to PulseAudio for audio playback.${coloroff}";
								echo -e "Do you grant this permission?";
								select yn in "Yes" "No"; do
									case $yn in
										Yes )
											flatpak --user override net.newpipe.NewPipe --socket=pulseaudio;
											break;;
										No )
											break;;
										esac
									done
								echo -e "${red}NewPipe requires direct access to your GPU for hardware acceleration.${coloroff}";
								echo -e "Do you grant this permission?";
								select yn in "Yes" "No"; do
									case $yn in
										Yes )
											flatpak --user override net.newpipe.NewPipe --device=dri;
											break;;
										No )
											break;;
										esac
									done
								break;;
							No )
								break;;
						esac
					done
				echo -e "Jellyfin Media Player? (Flatpak)";
				select yn in "Yes" "No"; do
					case $yn in
							Yes )
								echo -e "${red}Installing Jellyfin Media Player...${coloroff}";
								flatpak --user install com.github.iwalton3.jellyfin-media-player;
								echo -e "${red}Jellyfin will not function without network access.${coloroff}";
								echo -e "Do you grant this permission?";
								select yn in "Yes" "No"; do
									case $yn in
										Yes )
											flatpak --user override com.github.iwalton3.jellyfin-media-player --share=network;
											break;;
										No )
											break;;
										esac
									done
								echo -e "${red}Jellyfin requires access to PulseAudio for audio playback.${coloroff}";
								echo -e "Do you grant this permission?";
								select yn in "Yes" "No"; do
									case $yn in
										Yes )
											flatpak --user override com.github.iwalton3.jellyfin-media-player --socket=pulseaudio;
											break;;
										No )
											break;;
										esac
									done
								break;;
							No )
								break;;
						esac
					done
				echo -e "Jellyfin MPV Shim? (Flatpak)";
				select yn in "Yes" "No"; do
					case $yn in
							Yes )
								echo -e "${red}Installing Jellyfin MPV Shim...${coloroff}";
								flatpak --user install com.github.iwalton3.jellyfin-mpv-shim;
								echo -e "${red}Jellyfin MPV Shim will not launch without access to the X11 windowing system.${coloroff}";
								echo -e "Do you grant this permission?";
								select yn in "Yes" "No"; do
									case $yn in
										Yes )
											flatpak --user override com.github.iwalton3.jellyfin-mpv-shim --socket=x11;
											break;;
										No )
											break;;
										esac
									done
								echo -e "${red}Jellyfin MPV Shim will not function without network access.${coloroff}";
								echo -e "Do you grant this permission?";
								select yn in "Yes" "No"; do
									case $yn in
										Yes )
											flatpak --user override com.github.iwalton3.jellyfin-mpv-shim --share=network;
											break;;
										No )
											break;;
										esac
									done
								echo -e "${red}Jellyfin MPV Shim requires access to PulseAudio for audio playback.${coloroff}";
								echo -e "Do you grant this permission?";
								select yn in "Yes" "No"; do
									case $yn in
										Yes )
											flatpak --user override com.github.iwalton3.jellyfin-mpv-shim --socket=pulseaudio;
											break;;
										No )
											break;;
										esac
									done
								echo -e "${red}Jellyfin MPV Shim requires direct access to your GPU for hardware acceleration.${coloroff}";
								echo -e "Do you grant this permission?";
								select yn in "Yes" "No"; do
									case $yn in
										Yes )
											flatpak --user override com.github.iwalton3.jellyfin-mpv-shim --device=dri;
											break;;
										No )
											break;;
										esac
									done
								break;;
							No )
								break;;
						esac
					done
				echo -e "Finamp? (Flatpak)";
				select yn in "Yes" "No"; do
					case $yn in
							Yes )
								echo -e "${red}Installing Finamp..${coloroff}";
								flatpak --user install com.unicornsonlsd.finamp;
								echo -e "${red}Finamp will not function without network access.${coloroff}";
								echo -e "Do you grant this permission?";
								select yn in "Yes" "No"; do
									case $yn in
										Yes )
											flatpak --user override com.unicornsonlsd.finamp --share=network;
											break;;
										No )
											break;;
										esac
									done
								echo -e "${red}Finamp requires access to PulseAudio for audio playback.${coloroff}";
								echo -e "Do you grant this permission?";
								select yn in "Yes" "No"; do
									case $yn in
										Yes )
											flatpak --user override com.unicornsonlsd.finamp --socket=pulseaudio;
											break;;
										No )
											break;;
										esac
									done
								break;;
							No )
								break;;
						esac
					done
				echo -e "MakeMKV? (Flatpak)";
				select yn in "Yes" "No"; do
					case $yn in
							Yes )
								echo -e "${red}Installing MakeMKV...${coloroff}";
								flatpak --user install com.makemkv.MakeMKV;
								echo -e "${red}MakeMKV requires access to your connected devices for ripping media from your disk drive.${coloroff}";
								echo -e "Do you grant this permission?";
								select yn in "Yes" "No"; do
									case $yn in
										Yes )
											flatpak --user override com.makemkv.MakeMKV --device=all;
											break;;
										No )
											break;;
										esac
									done
								echo -e "${red}MakeMKV requires network access for downloading & updating decryption keys.${coloroff}";
								echo -e "Do you grant this permission?";
								select yn in "Yes" "No"; do
									case $yn in
										Yes )
											flatpak --user override com.makemkv.MakeMKV --share=network;
											break;;
										No )
											break;;
										esac
									done
								break;;
							No )
								break;;
						esac
					done
				echo -e "Asunder? (Flatpak)";
				select yn in "Yes" "No"; do
					case $yn in
							Yes )
								echo -e "${red}Installing Asunder...${coloroff}";
								flatpak --user install ca.littlesvr.asunder;
								echo -e "${red}Asunder will not launch without access to the X11 windowing system.${coloroff}";
								echo -e "Do you grant this permission?";
								select yn in "Yes" "No"; do
									case $yn in
										Yes )
											flatpak --user override ca.littlesvr.asunder --socket=x11;
											break;;
										No )
											break;;
										esac
									done
								echo -e "${red}Asunder requires access to your connected devices for ripping media from your disk drive.${coloroff}";
								echo -e "Do you grant this permission?";
								select yn in "Yes" "No"; do
									case $yn in
										Yes )
											flatpak --user override ca.littlesvr.asunder --device=all;
											break;;
										No )
											break;;
										esac
									done
								echo -e "${red}Asunder requires network access for downloading & updating metadata.${coloroff}";
								echo -e "Do you grant this permission?";
								select yn in "Yes" "No"; do
									case $yn in
										Yes )
											flatpak --user override ca.littlesvr.asunder --share=network;
											break;;
										No )
											break;;
										esac
									done
								echo -e "${red}Asunder requires access to a directory on your system for saving media.${coloroff}";
								echo -e "By default, we can grant it access to its own folder located at ~/Music/Asunder";
								echo -e "${red}Make sure to set this as your destination folder in Asunder's "General" Preferences!${coloroff}";
								echo -e "Do you accept this?";
								select yn in "Yes" "No"; do
									case $yn in
										Yes )
											mkdir -p ~/Music/Asunder;
											flatpak --user override ca.littlesvr.asunder --filesystem=xdg-music/Asunder;
											break;;
										No )
											break;;
										esac
									done
								break;;
							No )
								break;;
						esac
					done
				break;;
			No )
				break;;
		esac
	done

	echo -e "Would you like to install software for content creation?";
	select yn in "Yes" "No"; do
		case $yn in
			Yes )
				echo -e "Audacity? (Flatpak)";
				select yn in "Yes" "No"; do
					case $yn in
							Yes )
								echo -e "${red}Removing RPM if already installed...${coloroff}";
								dnf remove audacity audacity-freeworld;
								echo -e "${red}Installing Audacity...${coloroff}";
								flatpak --user install org.audacityteam.Audacity;
								echo -e "${red}Audacity requires access to PulseAudio for audio input & playback.${coloroff}";
								echo -e "Do you grant this permission?";
								select yn in "Yes" "No"; do
									case $yn in
										Yes )
											flatpak --user override org.audacityteam.Audacity --socket=pulseaudio;
											break;;
										No )
											break;;
										esac
									done
								break;;
							No )
								break;;
						esac
					done
				echo -e "GIMP? (Flatpak)";
				select yn in "Yes" "No"; do
					case $yn in
							Yes )
								echo -e "${red}Removing RPM if already installed...${coloroff}";
								dnf remove gimp;
								echo -e "${red}Installing GIMP...${coloroff}";
								flatpak --user install org.gimp.GIMP;
								echo -e "${red}GIMP will not launch without access to the X11 windowing system.${coloroff}";
								echo -e "Do you grant this permission?";
								select yn in "Yes" "No"; do
									case $yn in
										Yes )
											flatpak --user override org.gimp.GIMP --socket=x11;
											break;;
										No )
											break;;
										esac
									done
								break;;
							No )
								break;;
						esac
					done
				echo -e "Inkscape? (Flatpak)";
				select yn in "Yes" "No"; do
					case $yn in
							Yes )
								echo -e "${red}Removing RPM if already installed...${coloroff}";
								dnf remove inkscape;
								echo -e "${red}Installing Inkscape...${coloroff}";
								flatpak --user install org.inkscape.Inkscape;
								break;;
							No )
								break;;
						esac
					done
				echo -e "Tux Paint? (Flatpak)";
				select yn in "Yes" "No"; do
					case $yn in
							Yes )
								echo -e "${red}Removing RPM if already installed...${coloroff}";
								dnf remove tuxpaint;
								echo -e "${red}Installing Tux Paint...${coloroff}";
								flatpak --user install org.tuxpaint.Tuxpaint;
								break;;
							No )
								break;;
						esac
					done
				echo -e "HandBrake? (Flatpak)";
				select yn in "Yes" "No"; do
					case $yn in
							Yes )
								echo -e "${red}Removing RPM if already installed...${coloroff}";
								dnf remove handbrake;
								echo -e "${red}Installing HandBrake...${coloroff}";
								flatpak --user install fr.handbrake.ghb;
								echo -e "${red}HandBrake requires direct access to your GPU for hardware acceleration.${coloroff}";
								echo -e "Do you grant this permission?";
								select yn in "Yes" "No"; do
									case $yn in
										Yes )
											flatpak --user override fr.handbrake.ghb --device=dri;
											break;;
										No )
											break;;
										esac
									done
								break;;
							No )
								break;;
						esac
					done
				echo -e "Kdenlive? (Flatpak)";
				select yn in "Yes" "No"; do
					case $yn in
							Yes )
								echo -e "${red}Removing RPM if already installed...${coloroff}";
								dnf remove kdenlive;
								echo -e "${red}Installing Kdenlive...${coloroff}";
								flatpak --user install org.kde.kdenlive;
								echo -e "${red}Kdenlive requires direct access to your GPU for hardware acceleration.${coloroff}";
								echo -e "Do you grant this permission?";
								select yn in "Yes" "No"; do
									case $yn in
										Yes )
											flatpak --user override org.kde.kdenlive --device=dri;
											break;;
										No )
											break;;
										esac
									done
								echo -e "${red}Kdenlive requires access to PulseAudio for audio playback.${coloroff}";
								echo -e "Do you grant this permission?";
								select yn in "Yes" "No"; do
									case $yn in
										Yes )
											flatpak --user override org.kde.kdenlive --socket=pulseaudio;
											break;;
										No )
											break;;
										esac
									done
								break;;
							No )
								break;;
						esac
					done		
				echo -e "OBS? (Flatpak)";
				select yn in "Yes" "No"; do
					case $yn in
							Yes )
								echo -e "${red}Removing RPM if already installed...${coloroff}";
								dnf remove obs-studio;
								echo -e "${red}Installing OBS...${coloroff}";
								flatpak --user install com.obsproject.Studio com.obsproject.Studio.Plugin.InputOverlay com.obsproject.Studio.Plugin.Gstreamer com.obsproject.Studio.Plugin.GStreamerVaapi com.obsproject.Studio.Plugin.CompositeBlur com.obsproject.Studio.Plugin.BackgroundRemoval;
								echo -e "${red}OBS requires direct access to your GPU for hardware acceleration.${coloroff}";
								echo -e "Do you grant this permission?";
								select yn in "Yes" "No"; do
									case $yn in
										Yes )
											flatpak --user override com.obsproject.Studio --device=dri;
											break;;
										No )
											break;;
										esac
									done
								echo -e "${red}OBS requires access to PulseAudio for audio input & playback.${coloroff}";
								echo -e "Do you grant this permission?";
								select yn in "Yes" "No"; do
									case $yn in
										Yes )
											flatpak --user override com.obsproject.Studio --socket=pulseaudio;
											break;;
										No )
											break;;
										esac
									done
								echo -e "${red}OBS requires access to your connected devices for recording via your webcam.${coloroff}";
								echo -e "Do you grant this permission?";
								select yn in "Yes" "No"; do
									case $yn in
										Yes )
											flatpak --user override com.obsproject.Studio --device=all;
											break;;
										No )
											break;;
										esac
									done
								echo -e "${red}OBS requires network access for streaming to online services.${coloroff}";
								echo -e "Do you grant this permission?";
								select yn in "Yes" "No"; do
									case $yn in
										Yes )
											flatpak --user override com.obsproject.Studio --share=network;
											break;;
										No )
											break;;
										esac
									done
								break;;
							No )
								break;;
						esac
					done
				break;;
			No )
				break;;
		esac
	done

	echo -e "Would you like to install software for Gaming?";
	select yn in "Yes" "No"; do
		case $yn in
			Yes )
				echo -e "Steam? (Flatpak)";
				select yn in "Yes" "No"; do
					case $yn in
							Yes )
								echo -e "${red}Removing RPM if already installed...${coloroff}";
								dnf remove steam;
								echo -e "${red}Installing Steam...${coloroff}";
								flatpak --user install com.valvesoftware.Steam com.valvesoftware.Steam.Utility.steamtinkerlaunch com.valvesoftware.Steam.CompatibilityTool.Proton-GE com.valvesoftware.Steam.Utility.InhibitScreensaver;
								echo -e "${red}Steam will not launch without access to the X11 windowing system.${coloroff}";
								echo -e "Do you grant this permission?";
								select yn in "Yes" "No"; do
									case $yn in
										Yes )
											flatpak --user override com.valvesoftware.Steam --nosocket=wayland --socket=fallback-x11;
											break;;
										No )
											break;;
										esac
									done
								echo -e "${red}Steam will not launch with hardened_malloc.${coloroff}";
								echo -e "Do you grant it an exception?";
								select yn in "Yes" "No"; do
									case $yn in
										Yes )
											flatpak --user override com.valvesoftware.Steam --nofilesystem=host-os --unset-env=LD_PRELOAD;
											break;;
										No )
											break;;
										esac
									done
								echo -e "${red}Steam will not function without network access.${coloroff}";
								echo -e "Do you grant this permission?";
								select yn in "Yes" "No"; do
									case $yn in
										Yes )
											flatpak --user override com.valvesoftware.Steam --share=network;
											break;;
										No )
											break;;
										esac
									done
								echo -e "${red}Steam requires access to PulseAudio for audio input & playback.${coloroff}";
								echo -e "Do you grant this permission?";
								select yn in "Yes" "No"; do
									case $yn in
										Yes )
											flatpak --user override com.valvesoftware.Steam --socket=pulseaudio;
											break;;
										No )
											break;;
										esac
									done
								echo -e "${red}Games will perform poorly without direct access to your GPU for hardware acceleration.${coloroff}";
								echo -e "Do you grant this permission?";
								select yn in "Yes" "No"; do
									case $yn in
										Yes )
											flatpak --user override com.valvesoftware.Steam --device=dri;
											break;;
										No )
											break;;
										esac
									done
								break;;
							No )
								break;;
						esac
					done
				echo -e "Lutris? (Flatpak)";
				select yn in "Yes" "No"; do
					case $yn in
							Yes )
								echo -e "${red}Removing RPM if already installed...${coloroff}";
								dnf remove lutris;
								echo -e "${red}Installing Lutris...${coloroff}";
								flatpak --user install net.lutris.Lutris;
								echo -e "${red}Lutris will not function without network access.${coloroff}";
								echo -e "Do you grant this permission?";
								select yn in "Yes" "No"; do
									case $yn in
										Yes )
											flatpak --user override net.lutris.Lutris --share=network;
											break;;
										No )
											break;;
										esac
									done
								echo -e "${red}Lutris requires access to PulseAudio for audio playback.${coloroff}";
								echo -e "Do you grant this permission?";
								select yn in "Yes" "No"; do
									case $yn in
										Yes )
											flatpak --user override net.lutris.Lutris --socket=pulseaudio;
											break;;
										No )
											break;;
										esac
									done
								echo -e "${red}Games will perform poorly without direct access to your GPU for hardware acceleration.${coloroff}";
								echo -e "Do you grant this permission?";
								select yn in "Yes" "No"; do
									case $yn in
										Yes )
											flatpak --user override net.lutris.Lutris --device=dri;
											break;;
										No )
											break;;
										esac
									done
								break;;
							No )
								break;;
						esac
					done
				echo -e "Prism Launcher? (Minecraft, Flatpak)";
				select yn in "Yes" "No"; do
					case $yn in
							Yes )
								echo -e "${red}Installing Prism Launcher...${coloroff}";
								flatpak --user install org.prismlauncher.PrismLauncher;
								echo -e "${red}Prism Launcher will not function without network access.${coloroff}";
								echo -e "Do you grant this permission?";
								select yn in "Yes" "No"; do
									case $yn in
										Yes )
											flatpak --user override org.prismlauncher.PrismLauncher --share=network;
											break;;
										No )
											break;;
										esac
									done
								echo -e "${red}Prism Launcher requires access to PulseAudio for audio playback.${coloroff}";
								echo -e "Do you grant this permission?";
								select yn in "Yes" "No"; do
									case $yn in
										Yes )
											flatpak --user override org.prismlauncher.PrismLauncher --socket=pulseaudio;
											break;;
										No )
											break;;
										esac
									done
								echo -e "${red}Prism Launcher will perform poorly without direct access to your GPU for hardware acceleration.${coloroff}";
								echo -e "Do you grant this permission?";
								select yn in "Yes" "No"; do
									case $yn in
										Yes )
											flatpak --user override org.prismlauncher.PrismLauncher --device=dri;
											break;;
										No )
											break;;
										esac
									done
								break;;
							No )
								break;;
						esac
					done
				echo -e "Sober? (Roblox, Flatpak)";
				select yn in "Yes" "No"; do
					case $yn in
							Yes )
								echo -e "${red}Installing Sober...${coloroff}";
								flatpak --user install https://sober.vinegarhq.org/sober.flatpakref;
								echo -e "${red}Sober will not function without network access.${coloroff}";
								echo -e "Do you grant this permission?";
								select yn in "Yes" "No"; do
									case $yn in
										Yes )
											flatpak --user override org.vinegarhq.Sober --share=network;
											break;;
										No )
											break;;
										esac
									done
								echo -e "${red}Sober requires access to PulseAudio for audio input & playback.${coloroff}";
								echo -e "Do you grant this permission?";
								select yn in "Yes" "No"; do
									case $yn in
										Yes )
											flatpak --user override org.vinegarhq.Sober --socket=pulseaudio;
											break;;
										No )
											break;;
										esac
									done
								echo -e "${red}Sober will perform poorly without direct access to your GPU for hardware acceleration.${coloroff}";
								echo -e "Do you grant this permission?";
								select yn in "Yes" "No"; do
									case $yn in
										Yes )
											flatpak --user override org.vinegarhq.Sober --device=dri;
											break;;
										No )
											break;;
										esac
									done
								break;;
							No )
								break;;
						esac
					done
				echo -e "Luanti? (Minetest, Flatpak)";
				select yn in "Yes" "No"; do
					case $yn in
							Yes )
								echo -e "${red}Installing Luanti...${coloroff}";
								flatpak --user install net.minetest.Minetest;
								echo -e "${red}Luanti will not launch without access to the X11 windowing system.${coloroff}";
								echo -e "Do you grant this permission?";
								select yn in "Yes" "No"; do
									case $yn in
										Yes )
											flatpak --user override net.minetest.Minetest --nosocket=wayland --socket=fallback-x11;
											break;;
										No )
											break;;
										esac
									done
								echo -e "${red}Luanti will not function without network access.${coloroff}";
								echo -e "Do you grant this permission?";
								select yn in "Yes" "No"; do
									case $yn in
										Yes )
											flatpak --user override net.minetest.Minetest --share=network;
											break;;
										No )
											break;;
										esac
									done
								echo -e "${red}Luanti requires access to PulseAudio for audio playback.${coloroff}";
								echo -e "Do you grant this permission?";
								select yn in "Yes" "No"; do
									case $yn in
										Yes )
											flatpak --user override net.minetest.Minetest --socket=pulseaudio;
											break;;
										No )
											break;;
										esac
									done
								echo -e "${red}Luanti will perform poorly without direct access to your GPU for hardware acceleration.${coloroff}";
								echo -e "Do you grant this permission?";
								select yn in "Yes" "No"; do
									case $yn in
										Yes )
											flatpak --user override net.minetest.Minetest --device=dri;
											break;;
										No )
											break;;
										esac
									done
								break;;
							No )
								break;;
						esac
					done
				echo -e "SuperTuxKart? (Flatpak)";
				select yn in "Yes" "No"; do
					case $yn in
							Yes )
								echo -e "${red}Installing SuperTuxKart...${coloroff}";
								flatpak --user install net.supertuxkart.SuperTuxKart;
								echo -e "${red}SuperTuxKart requires access to PulseAudio for audio playback.${coloroff}";
								echo -e "Do you grant this permission?";
								select yn in "Yes" "No"; do
									case $yn in
										Yes )
											flatpak --user override net.supertuxkart.SuperTuxKart --socket=pulseaudio;
											break;;
										No )
											break;;
										esac
									done
								echo -e "${red}SuperTuxKart will perform poorly without direct access to your GPU for hardware acceleration.${coloroff}";
								echo -e "Do you grant this permission?";
								select yn in "Yes" "No"; do
									case $yn in
										Yes )
											flatpak --user override net.supertuxkart.SuperTuxKart --device=dri;
											break;;
										No )
											break;;
										esac
									done
								echo -e "${red}SuperTuxKart requires network access for online multiplayer & downloading add-ons.${coloroff}";
								echo -e "Do you grant this permission?";
								select yn in "Yes" "No"; do
									case $yn in
										Yes )
											flatpak --user override net.supertuxkart.SuperTuxKart --share=network;
											break;;
										No )
											break;;
										esac
									done
								break;;
							No )
								break;;
						esac
					done
				break;;
			No )
				break;;
		esac
	done

	echo -e "Would you like to install software for compatibility with Windows Software?";
	echo -e "Recommended for Gaming!";
	select yn in "Yes" "No"; do
		case $yn in
			Yes )
				echo -e "WINE? (RPM)";
				select yn in "Yes" "No"; do
					case $yn in
							Yes )
								echo -e "${red}Installing WINE...${coloroff}";
								dnf install wine;
								dnf install winetricks;
								break;;
							No )
								break;;
						esac
					done
				echo -e "Bottles? (Flatpak)";
				select yn in "Yes" "No"; do
					case $yn in
							Yes )
								echo -e "${red}Installing Bottles...${coloroff}";
								flatpak --user install com.usebottles.bottles;
								echo -e "${red}Bottles will not function without network access.${coloroff}";
								echo -e "Do you grant this permission?";
								select yn in "Yes" "No"; do
									case $yn in
										Yes )
											flatpak --user override com.usebottles.bottles --share=network;
											break;;
										No )
											break;;
										esac
									done
								echo -e "${red}Bottles requires access to PulseAudio for audio input & playback.${coloroff}";
								echo -e "Do you grant this permission?";
								select yn in "Yes" "No"; do
									case $yn in
										Yes )
											flatpak --user override com.usebottles.bottles --socket=pulseaudio;
											break;;
										No )
											break;;
										esac
									done
								echo -e "${red}Software will perform poorly without direct access to your GPU for hardware acceleration.${coloroff}";
								echo -e "Do you grant this permission?";
								select yn in "Yes" "No"; do
									case $yn in
										Yes )
											flatpak --user override com.usebottles.bottles --device=dri;
											break;;
										No )
											break;;
										esac
									done
								break;;
							No )
								break;;
						esac
					done
				echo -e "Protontricks? (Flatpak)";
				select yn in "Yes" "No"; do
					case $yn in
							Yes )
								echo -e "${red}Installing Protontricks...${coloroff}";
								flatpak --user install com.github.Matoking.protontricks;
								break;;
							No )
								break;;
						esac
					done
				echo -e "ProtonUp-Qt? (Flatpak)";
				select yn in "Yes" "No"; do
					case $yn in
							Yes )
								echo -e "${red}Installing ProtonUp-Qt...${coloroff}";
								flatpak --user install net.davidotek.pupgui2;
								echo -e "${red}ProtonUp-Qt will not function without network access.${coloroff}";
								echo -e "Do you grant this permission?";
								select yn in "Yes" "No"; do
									case $yn in
										Yes )
											flatpak --user override net.davidotek.pupgui2 --share=network;
											break;;
										No )
											break;;
										esac
									done
								break;;
							No )
								break;;
						esac
					done
				break;;
			No )
				break;;
		esac
	done

	echo -e "Would you like to install any Emulators?";
	select yn in "Yes" "No"; do
		case $yn in
			Yes )
				echo -e "RetroArch? (Flatpak)";
				select yn in "Yes" "No"; do
					case $yn in
							Yes )
								echo -e "${red}Installing RetroArch...${coloroff}";
								flatpak --user install org.libretro.RetroArch;
								echo -e "${red}RetroArch will not function without network access.${coloroff}";
								echo -e "Do you grant this permission?";
								select yn in "Yes" "No"; do
									case $yn in
										Yes )
											flatpak --user override org.libretro.RetroArch --share=network;
											break;;
										No )
											break;;
										esac
									done
								echo -e "${red}RetroArch requires access to PulseAudio for audio playback.${coloroff}";
								echo -e "Do you grant this permission?";
								select yn in "Yes" "No"; do
									case $yn in
										Yes )
											flatpak --user override org.libretro.RetroArch --socket=pulseaudio;
											break;;
										No )
											break;;
										esac
									done
								echo -e "${red}RetroArch will perform poorly without direct access to your GPU for hardware acceleration.${coloroff}";
								echo -e "Do you grant this permission?";
								select yn in "Yes" "No"; do
									case $yn in
										Yes )
											flatpak --user override org.libretro.RetroArch --device=dri;
											break;;
										No )
											break;;
										esac
									done
								echo -e "${red}RetroArch requires access to a directory on your system for scanning & playing ROMs.${coloroff}";
								echo -e "By default, we can grant it read-only access to ~/ROMs";
								echo -e "Do you accept this?";
								select yn in "Yes" "No"; do
									case $yn in
										Yes )
											mkdir -p ~/ROMs;
											flatpak --user override org.libretro.RetroArch --filesystem=~/ROMs:ro;
											break;;
										No )
											break;;
										esac
									done
								break;;
							No )
								break;;
						esac
					done
				echo -e "Dolphin? (GameCube/Wii, Flatpak)";
				select yn in "Yes" "No"; do
					case $yn in
							Yes )
								echo -e "${red}Installing Dolphin...${coloroff}";
								flatpak --user install org.DolphinEmu.dolphin-emu;
								echo -e "${red}Dolphin will not launch without access to the X11 windowing system.${coloroff}";
								echo -e "Do you grant this permission?";
								select yn in "Yes" "No"; do
									case $yn in
										Yes )
											flatpak --user override org.DolphinEmu.dolphin-emu --socket=x11;
											break;;
										No )
											break;;
										esac
									done
								echo -e "${red}Dolphin will not launch with hardened_malloc.${coloroff}";
								echo -e "Do you grant it an exception?";
								select yn in "Yes" "No"; do
									case $yn in
										Yes )
											flatpak --user override org.DolphinEmu.dolphin-emu --nofilesystem=host-os --unset-env=LD_PRELOAD;
											break;;
										No )
											break;;
										esac
									done
								echo -e "${red}Dolphin requires access to PulseAudio for audio playback.${coloroff}";
								echo -e "Do you grant this permission?";
								select yn in "Yes" "No"; do
									case $yn in
										Yes )
											flatpak --user override org.DolphinEmu.dolphin-emu --socket=pulseaudio;
											break;;
										No )
											break;;
										esac
									done
								echo -e "${red}Dolphin will perform poorly without direct access to your GPU for hardware acceleration.${coloroff}";
								echo -e "Do you grant this permission?";
								select yn in "Yes" "No"; do
									case $yn in
										Yes )
											flatpak --user override org.DolphinEmu.dolphin-emu --device=dri;
											break;;
										No )
											break;;
										esac
									done
								echo -e "${red}Dolphin requires network access for online multiplayer & other functionality.${coloroff}";
								echo -e "Do you grant this permission?";
								select yn in "Yes" "No"; do
									case $yn in
										Yes )
											flatpak --user override org.DolphinEmu.dolphin-emu --share=network;
											break;;
										No )
											break;;
										esac
									done
								break;;
							No )
								break;;
						esac
					done
				echo -e "PPSSPP? (PSP, Flatpak)";
				select yn in "Yes" "No"; do
					case $yn in
							Yes )
								echo -e "${red}Installing PPSSPP...${coloroff}";
								flatpak --user install org.ppsspp.PPSSPP;
								echo -e "${red}PPSSPP will not launch without access to the X11 windowing system.${coloroff}";
								echo -e "Do you grant this permission?";
								select yn in "Yes" "No"; do
									case $yn in
										Yes )
											flatpak --user override org.ppsspp.PPSSPP --socket=x11;
											break;;
										No )
											break;;
										esac
									done
								echo -e "${red}PPSSPP requires access to PulseAudio for audio playback.${coloroff}";
								echo -e "Do you grant this permission?";
								select yn in "Yes" "No"; do
									case $yn in
										Yes )
											flatpak --user override org.ppsspp.PPSSPP --socket=pulseaudio;
											break;;
										No )
											break;;
										esac
									done
								echo -e "${red}PPSSPP will perform poorly without direct access to your GPU for hardware acceleration.${coloroff}";
								echo -e "Do you grant this permission?";
								select yn in "Yes" "No"; do
									case $yn in
										Yes )
											flatpak --user override org.ppsspp.PPSSPP --device=dri;
											break;;
										No )
											break;;
										esac
									done
								echo -e "${red}PPSSPP requires network access for online multiplayer.${coloroff}";
								echo -e "Do you grant this permission?";
								select yn in "Yes" "No"; do
									case $yn in
										Yes )
											flatpak --user override org.ppsspp.PPSSPP --share=network;
											break;;
										No )
											break;;
										esac
									done
								echo -e "${red}PPSSPP requires access to a directory on your system for scanning & playing ROMs.${coloroff}";
								echo -e "By default, we can grant it read-only access to ~/ROMs";
								echo -e "Do you accept this?";
								select yn in "Yes" "No"; do
									case $yn in
										Yes )
											mkdir -p ~/ROMs;
											flatpak --user override org.ppsspp.PPSSPP --filesystem=~/ROMs:ro;
											break;;
										No )
											break;;
										esac
									done
								break;;
							No )
								break;;
						esac
					done
				break;;
			No )
				break;;
		esac
	done

	echo -e "Would you like to install a VPN?";
	select yn in "Yes" "No"; do
		case $yn in
			Yes )
				echo -e "IVPN? (RPM)";
				select yn in "Yes" "No"; do
					case $yn in
							Yes )
								echo -e "${red}Adding IVPN's Repository...${coloroff}";
								dnf config-manager addrepo --from-repofile='https://repo.ivpn.net/stable/fedora/generic/ivpn.repo';
								echo -e "${red}Updating DNF Cache...${coloroff}";
								dnf update --refresh;
								echo -e "${red}Installing IVPN...${coloroff}";
								dnf install ivpn ivpn-ui;
								break;;
							No )
								break;;
						esac
					done
				echo -e "Mullvad? (RPM)";
				select yn in "Yes" "No"; do
					case $yn in
							Yes )
								echo -e "${red}Adding Mullvad's Repository...${coloroff}";
								dnf config-manager addrepo --from-repofile='https://repository.mullvad.net/rpm/stable/mullvad.repo';
								echo -e "${red}Updating DNF Cache...${coloroff}";
								dnf update --refresh;
								echo -e "${red}Installing Mullvad...${coloroff}";
								dnf install mullvad-vpn;
								break;;
							No )
								break;;
						esac
					done
				echo -e "ProtonVPN? (Flatpak)";
				select yn in "Yes" "No"; do
					case $yn in
							Yes )
								echo -e "${red}Installing ProtonVPN...${coloroff}";
								flatpak --user install com.protonvpn.www;
								echo -e "${red}ProtonVPN will not function without network access.${coloroff}";
								echo -e "Do you grant this permission?";
								select yn in "Yes" "No"; do
									case $yn in
										Yes )
											flatpak --user override com.protonvpn.www --share=network;
											break;;
										No )
											break;;
										esac
									done
								break;;
							No )
								break;;
						esac
					done
				break;;
			No )
				break;;
		esac
	done

	echo -e "Would you like to install software for productivity?";
	select yn in "Yes" "No"; do
		case $yn in
			Yes )
				echo -e "Obsidian? (Flatpak)";
				select yn in "Yes" "No"; do
					case $yn in
							Yes )
								echo -e "${red}Installing Obsidian...${coloroff}";
								flatpak --user install md.obsidian.Obsidian;
								echo -e "${red}Obsidian requires network access for Sync & add-on installation/updates..${coloroff}";
								echo -e "Do you grant this permission?";
								select yn in "Yes" "No"; do
									case $yn in
										Yes )
											flatpak --user override md.obsidian.Obsidian --share=network;
											break;;
										No )
											break;;
										esac
									done
								echo -e "${red}Obsidian requires access to a directory on your system for saving notes.${coloroff}";
								echo -e "By default, we can grant it access to its own folder located at ~/Documents/Obsidian";
								echo -e "${red}Make sure to set this as your vault location during Obsidian's Set-up!${coloroff}";
								echo -e "Do you accept this?";
								select yn in "Yes" "No"; do
									case $yn in
										Yes )
											mkdir -p ~/Documents/Obsidian;
											flatpak --user override md.obsidian.Obsidian --filesystem=xdg-documents/Obsidian;
											break;;
										No )
											break;;
										esac
									done
								break;;
							No )
								break;;
						esac
					done
				echo -e "LibreOffice? (Flatpak)";
				select yn in "Yes" "No"; do
					case $yn in
							Yes )
								echo -e "${red}Removing RPM if already installed...${coloroff}";
								dnf remove libreoffice-core;
								echo -e "${red}Installing LibreOffice..${coloroff}";
								flatpak --user install org.libreoffice.LibreOffice;
								break;;
							No )
								break;;
						esac
					done								
				echo -e "OnlyOffice? (Flatpak)";
				select yn in "Yes" "No"; do
					case $yn in
							Yes )
								echo -e "${red}Installing OnlyOffice...${coloroff}";
								flatpak --user install org.onlyoffice.desktopeditors;
								echo -e "${red}OnlyOffice will not launch without access to the X11 windowing system.${coloroff}";
								echo -e "Do you grant this permission?";
								select yn in "Yes" "No"; do
									case $yn in
										Yes )
											flatpak --user override org.onlyoffice.desktopeditors --socket=x11;
											break;;
										No )
											break;;
										esac
									done
								break;;
							No )
								break;;
						esac
					done
				break;;
			No )
				break;;
		esac
	done

	echo -e "${red}Cleaning up DNF...${coloroff}";
	dnf autoremove;
	dnf clean all;

	echo -e "${red}Updating DNF Cache...${coloroff}";
	dnf update --refresh;

	echo -e "${red}Updating Flatpak Cache...${coloroff}";
	flatpak --system update;
	flatpak --user update;

	echo -e "${red}Updating Firejail...${coloroff}";
	firecfg;

fi;